/*
 * File name	= OISearchSqls.java
 * Package		= com.oifm.search
 * Created on 	= Aug 14, 2005
 * Created by	= Oscar
 * Copyright	= Scandent Group
 *
 */

package com.oifm.search;

import com.oifm.common.OILabelConstants;


public class OISearchSqls {
	public static final String QRY_SIMPLE_SEARCH_SU_SELECT = "SELECT ROWNUM NUM, S.SURVEYID ID, S.NAME TITLE, S.DESCRIPTION, S.CREATED_BY, CM.DESCRIPTION AS NICKNAME, TO_CHAR(S.CREATED_ON,'"+ OILabelConstants.DISPLAY_DATE_FORMAT +"') AS CREATED_ON FROM OI_SU_SURVEY S, OI_AD_PROFILE P, OI_AD_CODE_MASTER CM WHERE S.CREATED_BY = P.USERID AND P.DIVISIONCODE = CM.VALUE AND CM.TYPE = 'DIVISION_CODE' AND ACTIVE = 'Y' AND ((NVL(PUBLISHED_ST,'N') = 'N' AND TRUNC(SYSDATE) BETWEEN START_ON AND EXPIRY_ON) OR (NVL(PUBLISHED_ST,'N') = 'Y')) AND (S.SECURITY = \'N\' OR (S.SECURITY = \'Y\' AND S.SURVEYID IN (SELECT SURVEYID FROM OI_SU_MEMBERS WHERE USERID = ?))) AND (";
	public static final String QRY_SIMPLE_SEARCH_SU_NAME = "UPPER(S.NAME) LIKE UPPER('%";
	public static final String QRY_SIMPLE_SEARCH_SU_DESC = "UPPER(S.DESCRIPTION) LIKE UPPER('%";
	public static final String QRY_SIMPLE_SEARCH_SU_SUMMARY = "UPPER(S.SUMMARY) LIKE UPPER('%";
	
	public static final String QRY_SIMPLE_SEARCH_CP_SELECT = "SELECT ROWNUM NUM, C.PAPERID ID, C.TITLE, C.DESCRIPTION, C.CREATED_BY, CM.DESCRIPTION AS NICKNAME, TO_CHAR(C.CREATED_ON,'"+ OILabelConstants.DISPLAY_DATE_FORMAT +"') AS CREATED_ON FROM OI_CP_PAPER C, OI_AD_PROFILE P, OI_AD_CODE_MASTER CM WHERE C.CREATED_BY = P.USERID AND P.DIVISIONCODE = CM.VALUE AND CM.TYPE = 'DIVISION_CODE' AND ACTIVE = '1' AND ((NVL(PUBLISHED_ST,'N') = 'N' AND TRUNC(SYSDATE) BETWEEN FROM_DT AND TO_DT) OR (PUBLISHED_ON IS NOT NULL AND TO_DATE(PUBLISHED_ON) <= TO_DATE(SYSDATE))) AND (C.SECURITY = \'U\' OR (C.SECURITY = \'R\' AND C.PAPERID IN (SELECT PAPERID FROM OI_CP_MEMBERS WHERE USERID = ?))) AND (";
	public static final String QRY_SIMPLE_SEARCH_CP_TITLE = "UPPER(C.TITLE) LIKE UPPER('%";
	public static final String QRY_SIMPLE_SEARCH_CP_DESC = "UPPER(C.DESCRIPTION) LIKE UPPER('%";
	public static final String QRY_SIMPLE_SEARCH_CP_SUMMARY = "UPPER(C.SUMMARY) LIKE UPPER('%";
	
	public static final String QRY_SIMPLE_SEARCH_FM_SELECT = "SELECT ROWNUM NUM, T.THREADID ID, T.TITLE, P.POSTING DESCRIPTION, P.POSTED_BY CREATED_BY, P.NICKNAME, TO_CHAR(T.CREATED_ON,'"+ OILabelConstants.DISPLAY_DATE_FORMAT +"') AS CREATED_ON FROM OI_FM_THREAD T LEFT JOIN OI_FM_POSTS P ON (T.THREADID = P.THREADID) WHERE T.MODERATION_STAT = 'Y' AND P.MODERATION_STAT = 'Y' AND (T.SECURITY = 'N' OR (T.SECURITY = 'Y' AND T.THREADID IN (SELECT THREADID FROM OI_FM_THREAD_GROUPS TG LEFT JOIN OI_FM_GROUPMEMBERS GM  ON (USERID = ? AND TG.GROUPID = GM.GROUPID)))) AND (";
	public static final String QRY_SIMPLE_SEARCH_FM_TITLE = "UPPER(T.TITLE) LIKE UPPER('%";
	public static final String QRY_SIMPLE_SEARCH_FM_POSTING = "UPPER(P.POSTING) LIKE UPPER('%";
	
	// Added by Oscar for Enhancement 3
	public static final String QRY_SIMPLE_SEARCH_BG_SELECT = "SELECT ROWNUM NUM, E.ENTRY_ID || '&blogId='|| E.BLOG_ID ID, E.TITLE, NVL(E.ENTRY_EXCEPT, E.ENTRY_BODY) DESCRIPTION, E.CREATED_BY, P.NICKNAME, TO_CHAR(E.CREATED_ON, '"+ OILabelConstants.DISPLAY_DATE_FORMAT +"') CREATED_ON FROM OI_BG_ENTRY E LEFT JOIN OI_AD_PROFILE P ON (E.CREATED_BY = P.USERID) WHERE (";
	public static final String QRY_SIMPLE_SEARCH_BG_TAG = "UPPER(E.TAGS) LIKE UPPER('%";
	public static final String QRY_SIMPLE_SEARCH_BG_ENTRY_EXCERPT = "UPPER(E.ENTRY_EXCEPT) LIKE UPPER('%";
	public static final String QRY_SIMPLE_SEARCH_BG_ENTRY_BODY = "UPPER(E.ENTRY_BODY) LIKE UPPER('%";
	public static final String QRY_SIMPLE_SEARCH_BG_TITLE = "UPPER(E.TITLE) LIKE UPPER('%";
	// End added by Oscar
	
	public static final String QRY_SIMPLE_SEARCH_CLOSE_OR = "%\') OR ";
	public static final String QRY_SIMPLE_SEARCH_CLOSE = "%\'))";
	
	public static final String QRY_COUNT = "SELECT COUNT(*) COUNT FROM ( ";
	public static final String QRY_ROW1 = "SELECT * FROM ( ";
	public static final String QRY_ROW2 = " ) WHERE NUM >= ? AND NUM <= ? ";
	
	public static final String QRY_NUM_PER_PAGE = "SELECT VALUE FROM OI_AD_CONFIGURATION WHERE TAG = \'PAGESIZE\'";
	
	public static final String QRY_ADVANCED_SEARCH_SU_POST_OPEN=" and S.START_ON>(SYSDATE - (";
	public static final String QRY_ADVANCED_SEARCH_CP_POST_OPEN=" and C.FROM_DT>(SYSDATE - (";
	public static final String QRY_ADVANCED_SEARCH_FM_POST_OPEN=" and P.POSTED_ON>(SYSDATE - (";
	public static final String QRY_ADVANCED_SEARCH_BG_POST_OPEN=" and E.CREATED_ON>(SYSDATE - (";
	public static final String QRY_ADVANCED_SEARCH_SU_POST_CLOSE=" ))";
	public static final String QRY_ADVANCED_SEARCH_FM_POST_OPEN1=" and (select count(*) from OI_FM_POSTS countPost where countPost.POSTED_ON>(SYSDATE - (";
	public static final String QRY_ADVANCED_SEARCH_FM_POST_OPEN2=" and countPost.THREADID=P.THREADID)>=";
	public static final String QRY_ADVANCED_SEARCH_FM_POST_OPEN3=" and countPost.THREADID=P.THREADID)=";
	public static final String QRY_ADVANCED_SEARCH_FM_POST_OPEN4=" and (select count(*) from OI_FM_POSTS countPost where  countPost.THREADID=P.THREADID)>=";
	public static final String QRY_ADVANCED_SEARCH_FM_POST_OPEN5=" and (select count(*) from OI_FM_POSTS countPost where  countPost.THREADID=P.THREADID)=";
	
	public static final String QRY_ADVANCED_SEARCH_BY_USER  = "SELECT ROWNUM NUM, T.THREADID ID, T.TITLE, P.POSTING DESCRIPTION, T.CREATED_BY, TO_CHAR(T.CREATED_ON,'"+ OILabelConstants.DISPLAY_DATE_FORMAT +"') AS CREATED_ON,P.NICKNAME FROM OI_FM_THREAD T LEFT JOIN OI_FM_POSTS P ON (T.THREADID = P.THREADID) WHERE (T.SECURITY = 'N' OR (T.SECURITY = 'Y' AND T.THREADID IN (SELECT THREADID FROM OI_FM_THREAD_GROUPS TG LEFT JOIN OI_FM_GROUPMEMBERS GM  ON (USERID = ";
	public static final String QRY_ADVANCED_SEARCH_BY_USER1 = " AND TG.GROUPID = GM.GROUPID)))) and UPPER(P.NICKNAME) LIKE UPPER('%";
	public static final String QRY_ADVANCED_SEARCH_BY_USER2 = "%')";
}
