/*******************************************************************************************
* Title 		: OIHomeSqls.java
* Description 	: This Sql file contains the query to be manipulated in Home Module.     
* Author		: Suresh Kumar.R 
* Version No 	: 1.0
* Date Created 	: 01 - Aug -2005
* Copyright 	: Scandent Group
*********************************************************************************************/

package com.oifm.home;

import com.oifm.survey.OISurveyConstants;


public interface OIHomeSqls  
{
	 public static final String QRY_POLL_VIEW = " SELECT POLLID,TITLE,QUESTION, ANSWER1, ANSWER2, ANSWER3, ANSWER4, ANSWER5,MULTIPLE_ANS,SHOW_RESULT,PUBLISHED  FROM OI_PL_POLL  "+ 
	 							 		   " WHERE TRUNC(SYSDATE) BETWEEN TRUNC(START_ON) AND TRUNC(EXPIRY_ON) ";
	 
	 public static final String QRY_CNT_POLL = "SELECT COUNT(*) FROM OI_PL_RESPONSE WHERE POLLID = ? ";
	 
	 public static final String QRY_UPD_RES_POLL= " UPDATE OI_PL_RESPONSE SET ";
	 
	 public static final String QRY_WHR_POLL = " WHERE POLLID = ";
	 
	 public static final String QRY_INS_POLL="INSERT INTO OI_PL_RESPONSE(RESPONSEID,POLLID, RESPONSE1, RESPONSE2, RESPONSE3,  RESPONSE4, RESPONSE5) "+
	 										  "	VALUES (SEQ_OI_PL_RESPONSEID.NEXTVAL,?,?,?,?,?,?) ";
	 
	 //public static final String READ_LATEST_SURVEY = " SELECT OSS1.* FROM (SELECT SURVEYID, OSS.NAME, OSS.START_ON,OSS.EXPIRY_ON,OSS.DESCRIPTION FROM OI_SU_SURVEY OSS where ACTIVE='Y' and SECURITY='N' and PUBLISHED_ST='N'  order by START_ON desc,surveyID desc) OSS1 WHERE rownum <=3";
	  
	 //public static final String READ_LATEST_SURVEY = "SELECT OSS1.* FROM (select * from( SELECT OSS.SURVEYID, OSS.NAME, OSS.START_ON,OSS.EXPIRY_ON,OSS.DESCRIPTION FROM OI_SU_SURVEY OSS, (SELECT SURVEYID, USERID FROM OI_SU_MEMBERS WHERE UPPER(USERID) = UPPER(?) ) OM, (SELECT CPSUID, STATUS FROM OI_CPSU_DRAFTS WHERE DRAFT_TYPE = '"+OISurveyConstants.SURVEY_DOC+"' AND UPPER(USERID) = UPPER(?)) OD WHERE OSS.SURVEYID = OD.CPSUID(+) AND OSS.SURVEYID = OM.SURVEYID(+) AND NVL(PUBLISHED_ST,'N') = 'N' AND OSS.ACTIVE = 'Y' AND ((UPPER(OM.USERID )= UPPER(?) AND OSS.SECURITY = 'Y') OR OSS.SECURITY = 'N') AND TRUNC(SYSDATE) BETWEEN START_ON AND EXPIRY_ON group by START_ON,OSS.SURVEYID, NAME, DESCRIPTION,EXPIRY_ON) order by START_ON desc,SURVEYID ) OSS1 WHERE rownum <=3";
	 public static final String READ_LATEST_SURVEY = "SELECT OSS1.* FROM (SELECT * FROM (SELECT OSS.SURVEYID, OSS.NAME, OSS.START_ON,OSS.EXPIRY_ON,OSS.DESCRIPTION FROM OI_SU_SURVEY OSS, (SELECT CPSUID, STATUS FROM OI_CPSU_DRAFTS WHERE DRAFT_TYPE = '"+OISurveyConstants.SURVEY_DOC+"' AND UPPER(USERID) = UPPER(?)) OD WHERE OSS.SURVEYID = OD.CPSUID(+) AND NVL(PUBLISHED_ST,'N') = 'N' AND OSS.ACTIVE = 'Y' AND ((Oi_Pkg.IS_SU_MEMBER(OSS.SURVEYID, ?) > 0 AND OSS.SECURITY = 'Y') OR OSS.SECURITY = 'N') AND TRUNC(SYSDATE) BETWEEN START_ON AND EXPIRY_ON GROUP BY START_ON,OSS.SURVEYID, NAME, DESCRIPTION,EXPIRY_ON) ORDER BY START_ON DESC,SURVEYID ) OSS1 WHERE ROWNUM <=3";
	 
	 public static final String READ_LATEST_BLOG = "SELECT * FROM ( SELECT ENTRY1.*,NVL(ENTRY2.ENTRY_EXCEPT,SUBSTR(ENTRY2.ENTRY_BODY,1,50)) ENTRYBODY,ENTRY2.TITLE ENTRY_TITLE,ENTRY2.CREATED_ON,ENTRY2.IMAGE_NAME FROM (SELECT ENTRY.ENTRY_ID,ENTRY.BLOG_ID,BLOG.TITLE BLOG_TITLE FROM OI_BG_ENTRY ENTRY LEFT OUTER JOIN OI_BG_BLOG BLOG ON BLOG.BLOG_ID = ENTRY.BLOG_ID WHERE UPPER(ENTRY.STATUS)='P' GROUP BY ENTRY.ENTRY_ID,ENTRY.BLOG_ID,BLOG.TITLE) ENTRY1,OI_BG_ENTRY ENTRY2  WHERE ENTRY2.BLOG_ID = ENTRY1.BLOG_ID AND ENTRY2.ENTRY_ID = ENTRY1.ENTRY_ID  ORDER BY ENTRY2.CREATED_ON DESC,ENTRY1.ENTRY_ID,ENTRY1.BLOG_ID ) WHERE ROWNUM<=3"; 

	 public static final String GET_TAG = "SELECT TAG_WORDS FROM OI_AD_PROFILE WHERE USERID=? ";

	 public static final String UPDATE_TAG = "UPDATE OI_AD_PROFILE SET TAG_WORDS=? WHERE USERID=? ";
	 
}
