/*
 * File name	= OIAuditTrailSqls.java
 * Package		= com.oifm.useradmin
 * Created on 	= Aug 21, 2005
 * Created by	= Oscar
 * Copyright	= Scandent Group
 *
 */

package com.oifm.useradmin;


public class OIAuditTrailSqls {
	// SQL query to retrieve audit transaction
	public final static String QRY_AUDIT_TRANSACTION = "SELECT P1.USERID USERID, P1.NICKNAME NICKNAME, AT.TRANSACTION_TYPE, TO_CHAR(AT.TRANSACTION_ON,'DD-Mon-YYYY HH:MI AM') DATETIME, P2.USERID POSTUSERID, P2.NICKNAME POSTNICKNAME, TO_CHAR(AT.POSTEDON,'DD-Mon-YYYY HH:MI AM') POSTDATETIME, AT.THREADID, AT.POSTED_CONTENT, AT.MODERATED_CONTENT FROM OI_AD_AUDITTRAIL AT, OI_AD_PROFILE P1, OI_AD_PROFILE P2 WHERE AT.TRANSACTION_BY = P1.USERID AND AT.POSTEDBY = P2.USERID AND AT.TRANSACTION_TYPE LIKE ? AND TRUNC(AT.TRANSACTION_ON) BETWEEN TO_DATE(?) AND TO_DATE(?) ORDER BY AT.TRANSACTION_ON DESC";
}
