/*
 * File name	= OIRankingSqls.java
 * Package		= com.oifm.useradmin
 * Created on 	= Aug 17, 2005
 * Created by	= Oscar
 * Copyright	= Scandent Group
 *
 */

package com.oifm.useradmin;


public class OIRankingSqls {
	public static final String WEBSITE_RANKING = "SELECT * FROM (SELECT ROWNUM NUM, USERID, NAME, TOTAL_POSTS, TOTAL_PAPERS, TOTAL_SURVEYS, TOTAL FROM (SELECT USERID, NAME, SUM(POSTS) TOTAL_POSTS,SUM(PAPERS) TOTAL_PAPERS,SUM(SURVEYS) TOTAL_SURVEYS, SUM(POSTS)+SUM(PAPERS)+SUM(SURVEYS) TOTAL FROM (SELECT USERID, NAME,COUNT(DISTINCT POSTID) POSTS, 0 PAPERS, 0 SURVEYS   FROM OI_AD_PROFILE,OI_FM_POSTS WHERE USERID=POSTED_BY AND MONTHS_BETWEEN(SYSDATE, POSTED_ON) <= ? GROUP BY USERID, NAME HAVING COUNT(POSTID) > 0 UNION ALL SELECT P.USERID, P.NAME,0 POSTS, COUNT(DISTINCT C.PAPERID) PAPERS, 0 SURVEYS FROM OI_AD_PROFILE P,OI_CP_PAPER C,OI_CP_FEEDBACK F WHERE P.USERID=F.USERID AND C.PAPERID=F.PAPERID AND C.SECURITY='R' AND MONTHS_BETWEEN(SYSDATE, FEEDBACK_ON) <= ? GROUP BY P.USERID, P.NAME HAVING COUNT(C.PAPERID) > 0 UNION ALL SELECT P.USERID, P.NAME,0 POSTS, 0 PAPERS, COUNT(DISTINCT S.SURVEYID) SURVEYS FROM OI_AD_PROFILE P,OI_SU_SURVEY S,OI_SU_QUESTIONS Q,OI_SU_RESPONSE R WHERE P.USERID=R.USERID AND S.SURVEYID=Q.SURVEYID AND Q.QUESTIONID=R.QUESTIONID AND S.SECURITY='Y' AND MONTHS_BETWEEN(SYSDATE, R.RESPONSE_ON) <= ? GROUP BY P.USERID, P.NAME HAVING COUNT(S.SURVEYID) > 0) GROUP BY USERID, NAME ORDER BY TOTAL DESC)) WHERE NUM <= ?";
	public static final String POST_RANKING = "SELECT * FROM (SELECT ROWNUM NUM, USERID, NAME, POSTS FROM (SELECT USERID, NAME, COUNT(DISTINCT POSTID) POSTS FROM OI_AD_PROFILE,OI_FM_POSTS WHERE USERID = POSTED_BY AND MONTHS_BETWEEN(SYSDATE, POSTED_ON) <= ? GROUP BY USERID, NAME HAVING COUNT(POSTID) > 0 ORDER BY POSTS DESC)) WHERE NUM <= ?";
	public static final String THREAD_RANKING = "SELECT * FROM (SELECT ROWNUM NUM, USERID, NAME, THREADS FROM (SELECT USERID, NAME, COUNT(DISTINCT THREADID) THREADS FROM OI_AD_PROFILE, OI_FM_THREAD T WHERE USERID = CREATED_BY AND MONTHS_BETWEEN(SYSDATE, T.CREATED_ON) <= ? GROUP BY USERID, NAME HAVING COUNT(THREADID) > 0 ORDER BY THREADS DESC)) WHERE NUM <= ?";
	public static final String PAPER_RANKING = "SELECT * FROM (SELECT ROWNUM NUM, USERID, NAME, PAPERS FROM (SELECT P.USERID, P.NAME, COUNT(DISTINCT C.PAPERID) PAPERS FROM OI_AD_PROFILE P,OI_CP_PAPER C,OI_CP_FEEDBACK F WHERE P.USERID=F.USERID AND C.PAPERID=F.PAPERID AND C.SECURITY='R' AND MONTHS_BETWEEN(SYSDATE, FEEDBACK_ON) <= ? GROUP BY P.USERID, P.NAME HAVING COUNT(C.PAPERID) > 0 ORDER BY PAPERS DESC)) WHERE NUM <= ?";
	public static final String SURVEY_RANKING = "SELECT * FROM (SELECT ROWNUM NUM, USERID, NAME, SURVEYS FROM (SELECT P.USERID, P.NAME, COUNT(DISTINCT S.SURVEYID) SURVEYS FROM OI_AD_PROFILE P,OI_SU_SURVEY S,OI_SU_QUESTIONS Q,OI_SU_RESPONSE R WHERE P.USERID=R.USERID AND S.SURVEYID=Q.SURVEYID AND Q.QUESTIONID=R.QUESTIONID AND S.SECURITY='Y' AND MONTHS_BETWEEN(SYSDATE, R.RESPONSE_ON) <= ? GROUP BY P.USERID, P.NAME HAVING COUNT(S.SURVEYID) > 0 ORDER BY SURVEYS DESC)) WHERE NUM <= ?";
	public static final String WEBSITE_RANKING_TYPE = "select VALUE, DESCRIPTION from OI_AD_CODE_MASTER where TYPE = 'RANKING_TYPE_CODE'";
	public static final String RANK_LIST = " SELECT * FROM ( "
		+" Select B.Name NAME, C.Description Designation, ROUND(((SYSDATE-B.BIRTH_DT))/365) Age, "
		+" 	    D.DESCRIPTION School_Level, ROUND(((SYSDATE-B.JOINING_DT))/365) YrsInService, "
		+" 		Count(A.RANKID) Hits,ACTIONID"
		+" from OI_AD_SITERANK A,OI_AD_PROFILE B,OI_AD_CODE_MASTER C, OI_AD_CODE_MASTER D"
		+" Where A.USERID = B.USERID"
		+"   AND B.DESIGNATIONCODE = C.VALUE"
		+"   AND B.SCHOOLLVLCODE = D.VALUE"
		+"   AND C.TYPE = 'DESIGNATION_CODE'"
		+"   AND D.TYPE = 'SCHOOL_LEVEL'"
		+" GROUP BY B.Name, C.Description , ROUND(((SYSDATE-B.BIRTH_DT))/365), "
		+" 	    D.DESCRIPTION, ROUND(((SYSDATE-B.JOINING_DT))/365),ACTIONID)"
		+" ORDER BY hITS DESC";
}
