package com.oifm.blog;

public class OIIndividualBlogSqls
{
	// Individual Blog Home queries
	public static final String QRY_LIST_BLOG_ENTRIES = "SELECT * FROM ("
			+ "SELECT BLOG_ID, BGE.ENTRY_ID, TITLE, ADP.NAME, TO_CHAR(BGE.CREATED_ON, 'DD-Mon-YYYY HH24:MI:SS') CREATED_ON, ALLOW_COMMENTS, ENTRY_EXCEPT, ENTRY_BODY, IMAGE_NAME, NVL(COMCNT.CNT, 0) CNT "
			+ "FROM OI_BG_ENTRY BGE, OI_AD_PROFILE ADP, (SELECT ENTRY_ID, COUNT(*) CNT FROM OI_BG_ENTRY_COMMENTS GROUP BY ENTRY_ID) COMCNT WHERE ADP.USERID = BGE.CREATED_BY AND UPPER(STATUS) = 'P' AND COMCNT.ENTRY_ID(+) = BGE.ENTRY_ID AND BLOG_ID = ? ORDER BY BGE.CREATED_ON DESC) "
			+ "WHERE ROWNUM <= (SELECT NVL(NO_OF_POSTS_SHOW,4) FROM OI_BG_BLOG WHERE BLOG_ID = ?)";
	
	
	
	// Individual Blog Entry queries
	public static final String QRY_BLOG_ENTRY = "SELECT BGE.BLOG_ID, BGB.TITLE BLOG_TITLE, ENTRY_ID, BGE.TITLE, ADP.NAME, TO_CHAR(BGE.CREATED_ON, 'DD-Mon-YYYY') CREATED_ON, ALLOW_COMMENTS, ENTRY_EXCEPT, ENTRY_BODY, IMAGE_NAME "
			+ "FROM OI_BG_ENTRY BGE, OI_BG_BLOG BGB, OI_AD_PROFILE ADP WHERE BGE.BLOG_ID = BGB.BLOG_ID AND ADP.USERID = BGE.CREATED_BY AND ENTRY_ID = ?";
	
	public static final String QRY_BLOG_ENTRY_COMMENTS = "SELECT MESSAGE, TO_CHAR(EC.CREATED_ON, 'DD-Mon-YYYY HH24:MI:SS') CREATED_ON, NICKNAME FROM OI_BG_ENTRY_COMMENTS EC, OI_AD_PROFILE PR "
			+ "WHERE EC.CREATED_BY = PR.USERID AND ENTRY_ID = ? ORDER BY EC.CREATED_ON ASC";
	
	public static final String QRY_SAVE_COMMENT = "INSERT INTO OI_BG_ENTRY_COMMENTS (COMMENT_ID, ENTRY_ID, BLOG_ID, MESSAGE, CREATED_BY, CREATED_ON) "
			+ "VALUES (SEQ_OI_BG_COMMENTID.NEXTVAL, ?, ?, ?, ?, SYSDATE)";
	
	public static final String QRY_NOTIFY_EMAIL_RECIPIENTS = "SELECT DISTINCT ADP.EMAILID FROM OI_BG_AUTHORS BGA, OI_AD_PROFILE ADP "
			+ "WHERE BGA.USERID = ADP.USERID AND UPPER(BGA.NOTIFY_EMAIL) = 'Y' AND BGA.BLOG_ID = ?";
	
	public static final String QRY_NOTIFY_EMAIL_SUBJECT_BODY = "SELECT SUBJECT.SUBJECT, MAIL_BODY.MAIL_BODY "
			+ "FROM (SELECT DESCRIPTION SUBJECT FROM OI_AD_CODE_MASTER"
			+ "	     WHERE TYPE = 'MAIL_TEMPLATE' AND VALUE = 'BG_NOTIFICATION_MAIL_SUBJECT') SUBJECT,"
			+ "	    (SELECT DESCRIPTION MAIL_BODY FROM OI_AD_CODE_MASTER"
			+ "	     WHERE TYPE = 'MAIL_TEMPLATE' AND VALUE = 'BG_NOTIFICATION_MAIL_BODY') MAIL_BODY";
	
	
	// Individual Blog About Us queries
	public static final String QRY_AUTHOR_DETAILS_LIST = "SELECT BLOG_ID, BGA.USERID, ADP.NAME, NOTIFY_EMAIL, ABOUT_ME, ABOUT_IMAGE "
			+ "FROM OI_BG_AUTHORS BGA, OI_AD_PROFILE ADP "
			+ "WHERE BGA.USERID = ADP.USERID AND BLOG_ID = ?";
	
	public static final String QRY_AUTHOR_DETAILS = "SELECT BLOG_ID, BGA.USERID, ADP.NAME, NOTIFY_EMAIL, ABOUT_ME, ABOUT_IMAGE "
			+ "FROM OI_BG_AUTHORS BGA, OI_AD_PROFILE ADP "
			+ "WHERE BGA.USERID = ADP.USERID AND BLOG_ID = ? AND BGA.USERID = ?";
	
	public static final String QRY_AUTHOR_EDIT_DETAILS = "UPDATE OI_BG_AUTHORS SET NOTIFY_EMAIL = ?, ABOUT_IMAGE = ? WHERE BLOG_ID = ? AND USERID = ?";
	
	public static final String QRY_AUTHOR_GET_ABOUT_ME_FOR_UPDATE = "SELECT ABOUT_ME FROM OI_BG_AUTHORS WHERE BLOG_ID = ? AND USERID = ? FOR UPDATE";
	
	public static final String QRY_AUTHOR_REMOVE_PICTURE = "UPDATE OI_BG_AUTHORS SET ABOUT_IMAGE = '' WHERE BLOG_ID = ? AND USERID = ?";

	//get comment count
	public static final String QRY_COMMENT_COUNT = "select COUNT(DISTINCT COMMENT_ID) total_comment from OI_BG_ENTRY_COMMENTS where entry_id = ? group by entry_id";
}
