package com.oifm.forum;

import com.oifm.common.OILabelConstants;

public interface OIForumThreadPostsSqls {

//	To get Thread details
	public static final String	THREAD_DETAILS = "SELECT THREADID, TOPICID, TITLE, SECURITY, NVL(MODERATION_REQ, 'N') MODERATION_REQ, MODERATION_STAT, NVL(LOCKED, 'N') LOCKED, NVL(NICKNAME, CREATED_BY) NICKNAME, REPLIES, TO_CHAR(A.CREATED_ON, '"+OILabelConstants.DISPLAY_DATE_TIME_FORMAT+"')  CREATED_ON FROM OI_FM_THREAD A, OI_AD_PROFILE WHERE THREADID = ? AND CREATED_BY = USERID(+)";

//	To get the total posts for specific thread
	public static final String	THREAD_POSTS_CNT = "SELECT COUNT(POSTID) FROM OI_FM_POSTS WHERE MODERATION_STAT = 'Y' AND THREADID = ?";
	
//	To get list of postings for specific thread
	public static final String	THREAD_POSTS_LIST = "SELECT OFP1.* FROM (SELECT ROWNUM RN, OFP.* FROM (SELECT POSTID, POSTING, NICKNAME, SIGNATURE, POSTED_BY, POSTED_ON AS POSTED_ON_DATE,TO_CHAR(POSTED_ON, '"+OILabelConstants.DISPLAY_DATE_TIME_FORMAT+"') POSTED_ON_CHAR, HQREPLY,QUOTE_POSTING FROM OI_FM_POSTS OFP WHERE THREADID = ? AND MODERATION_STAT = 'Y' ORDER BY POSTED_ON ";
	
//	To get the category, board, topic info for specific thread
	public static final String	THREAD_CAT_BRD_TPC_INFO = "SELECT OFC.CATEGORYID, OFC.NAME CATEGORY, OFB.BOARDID, OFB.NAME BOARD, OFH.TOPICID, TOPICNAME TOPIC, OFT.THREADID, TITLE THREAD FROM OI_FM_CATEGORY OFC, OI_FM_BOARD OFB, OI_FM_TOPIC OFH, OI_FM_THREAD OFT WHERE OFC.CATEGORYID = OFB.CATEGORYID AND OFB.BOARDID = OFH.BOARDID AND OFH.TOPICID = OFT.TOPICID AND OFT.THREADID = ?";
	
//	To get the category, board, topic info for specific thread
	public static final String	THREAD_CAT_BRD_INFO = "SELECT unique OFC.CATEGORYID, OFC.NAME CATEGORY, OFB.BOARDID, OFB.NAME BOARD, OFH.TOPICID, TOPICNAME TOPIC ,OFH.TOPICDESC TOPICDESC FROM OI_FM_CATEGORY OFC, OI_FM_BOARD OFB, OI_FM_TOPIC OFH  WHERE OFC.CATEGORYID = OFB.CATEGORYID AND OFB.BOARDID = OFH.BOARDID AND OFH.TOPICID = ?";

//	To get Category, board, Topic hierarchy
	public static final String	CAT_BOARD_TOPIC_HRCY = "SELECT 	LEVEL, CHILD_ID ID, NAME FROM (SELECT '' PARENT_ID, 'C'||C.CATEGORYID CHILD_ID, C.NAME NAME FROM OI_FM_CATEGORY C UNION SELECT PARENT_ID, CHILD_ID, NAME FROM ( SELECT 'C'||B.CATEGORYID PARENT_ID, 'B'||B.BOARDID CHILD_ID, '..'||B.NAME NAME FROM OI_FM_BOARD B UNION SELECT 'B'||B.BOARDID PARENT_ID, ''||T.TOPICID CHILD_ID, '....'||T.TOPICNAME NAME FROM OI_FM_BOARD B, OI_FM_TOPIC T WHERE B.BOARDID=T.BOARDID) START WITH PARENT_ID like 'C%' CONNECT BY PRIOR CHILD_ID = PARENT_ID) START WITH PARENT_ID IS NULL  CONNECT BY PRIOR CHILD_ID = PARENT_ID ORDER SIBLINGS BY CHILD_ID";
	
//	To get new Thread ID
	public static final String	NEW_THREAD_ID = "SELECT SEQ_OI_FM_THREADID.NEXTVAL FROM DUAL";
	
//	To get new Posting ID
	public static final String	NEW_POSTING_ID = "SELECT SEQ_OI_FM_POSTID.NEXTVAL FROM DUAL";
	
//	To create thread info 
	public static final String CREATE_THREAD = "INSERT INTO OI_FM_THREAD (THREADID, TOPICID, TITLE, MODERATION_REQ, MODERATION_STAT, LASTPOST_ID, LASTPOST_ON, SECURITY, REPLIES, HITS, LOCKED, CREATED_BY, CREATED_ON) VALUES (?, ?, ?, ?, ?, ?, SYSDATE, ?, 0, 0, 'N', ?, SYSDATE)";

//	To Modify thread info 
	public static final String MODIFY_THREAD = "UPDATE OI_FM_THREAD SET TITLE = ?, MODERATION_REQ = ?, SECURITY = ? WHERE THREADID = ?";

//	To modify thread at modeeator level
	public static final String MODIFY_MOD_THREAD = "UPDATE OI_FM_THREAD SET TITLE = ? WHERE THREADID = ?";
		
//	To Modify postings count & last post id for specific thread
	public static final String MODIFY_LAST_POST_INFO = "UPDATE OI_FM_THREAD SET LASTPOST_ID = ?, LASTPOST_ON = SYSDATE, REPLIES = NVL(REPLIES, 0)+1 WHERE THREADID = ?";
//	To modify last posting info when moderation level
	public static final String MODIFY_MODERATION_LAST_POST_INFO = "UPDATE OI_FM_THREAD SET LASTPOST_ID = (SELECT MAX(POSTID) FROM OI_FM_POSTS WHERE THREADID = ? AND MODERATION_STAT = 'Y'), LASTPOST_ON = (SELECT MAX(POSTED_ON) FROM OI_FM_POSTS WHERE THREADID = ? AND MODERATION_STAT = 'Y'), REPLIES = (SELECT COUNT(POSTID) FROM OI_FM_POSTS WHERE THREADID = ? AND MODERATION_STAT = 'Y') WHERE THREADID = ?"; 

//	To delete thread info 
	public static final String DELETE_THREAD = "DELETE OI_FM_THREAD WHERE THREADID = ?";

//	To delete thread Bookmarks info 
	public static final String DELETE_THREAD_BOOKMARKS_STICKY = "DELETE OI_FM_BOOKMARKS WHERE THREADID = ?";
	
//	To delete posts belongs to specific thread 
	public static final String DELETE_THREAD_POSTS = "DELETE OI_FM_POSTS WHERE THREADID = ?";

//	To get the list of avaialble groups 
	public static final String GROUPS_LIST = "SELECT FG.GROUPID, FG.NAME FROM OI_FM_GROUPS FG";

//	To get the list of allocated groups for specific thread
	public static final String THREAD_GROUPS_LIST = "SELECT TG.GROUPID FROM OI_FM_THREAD_GROUPS TG WHERE TG.THREADID = ?";
	
//	To insert list of selected groups for specific thread	--THREADID, GROUPS List, THREADID
	public static final String INSERT_THREAD_GROUPS = "INSERT INTO OI_FM_THREAD_GROUPS (THREADGROUPID, GROUPID, THREADID) SELECT SEQ_OI_FM_THREADGROUPID.NEXTVAL, GROUPID, ? FROM OI_FM_GROUPS WHERE GROUPID IN (:GRPLST:) AND GROUPID NOT IN (SELECT GROUPID FROM OI_FM_THREAD_GROUPS WHERE THREADID = ?)";

//	To Delete the groups unselected for specific thread	--THREADID, GROUPS List 
	// Edited by Nimitta on Sep 15,2009
	public static final String DELETE_THREAD_GROUPS = "DELETE OI_FM_THREAD_GROUPS WHERE THREADID = ? ";
	//public static final String DELETE_THREAD_GROUPS = "DELETE OI_FM_THREAD_GROUPS WHERE THREADID = ? AND GROUPID NOT IN (:GRPLST:)";

//	To modify thread moderation status
	public static final String UPDATE_THREAD_MODERATION	= "UPDATE OI_FM_THREAD SET MODERATION_STAT = 'Y', MODERATED_BY = ?, MODERATED_ON = SYSDATE WHERE THREADID IN (:THREADIDS:)";
	public static final String UPDATE_THREAD_POST_MODERATION	= "UPDATE OI_FM_POSTS SET MODERATION_STAT = 'Y', MODERATED_BY = ?, MODERATED_ON = SYSDATE WHERE THREADID IN (:THREADIDS:)";

//	To delete threads when moderator rejects
	public static final String REJECT_THREAD_AUDIT_MODERATION	= "DELETE OI_AD_AUDITTRAIL WHERE THREADID IN (:THREADIDS:)";
	public static final String REJECT_THREAD_GROUPS_MODERATION	= "DELETE OI_FM_THREAD_GROUPS WHERE THREADID IN (:THREADIDS:)";
	public static final String REJECT_THREAD_MODERATION	= "DELETE OI_FM_THREAD WHERE THREADID IN (:THREADIDS:)";
	public static final String REJECT_THREAD_POST_MODERATION	= "DELETE OI_FM_POSTS WHERE THREADID IN (:THREADIDS:)";

//	To modify thread lock status
	public static final String UPDATE_THREAD_LOCK	= "UPDATE OI_FM_THREAD SET LOCKED = DECODE(NVL(LOCKED, 'N'), 'Y', 'N', 'N', 'Y') WHERE THREADID = ? ";
	
//	To get count of sticky threads 
	public static final String STICKY_THREAD_ALLOWED	= "SELECT 'Y' FROM (SELECT VALUE MAX_CNT FROM OI_AD_CONFIGURATION WHERE TAG = 'STICKYTHREADS') SM, (SELECT COUNT(THREADID) STK_CNT FROM OI_FM_BOOKMARKS WHERE USERID = ? AND BKM_STICKY = 'S') SC WHERE MAX_CNT > STK_CNT";

//	To get count of sticky threads 
	public static final String STICKY_THREAD_EXISTS	= "SELECT 'Y' FROM OI_FM_BOOKMARKS WHERE USERID = ? AND THREADID = ? AND BKM_STICKY = ?";

//	To get count of sticky threads 
	public static final String BOOKMARK_THREAD_ALLOWED	= "SELECT 'Y' FROM (SELECT VALUE MAX_CNT FROM OI_AD_CONFIGURATION WHERE TAG = 'BOOKMARKTHREADS') SM, (SELECT COUNT(THREADID) BKM_CNT FROM OI_FM_BOOKMARKS WHERE USERID = ? AND BKM_STICKY = 'B') SC WHERE MAX_CNT > BKM_CNT";
	
//	To get count of sticky threads 
	public static final String BOOKMARK_THREAD_EXISTS	= "SELECT 'Y' FROM OI_FM_BOOKMARKS WHERE USERID = ? AND THREADID = ? AND BKM_STICKY = ?";
	
//	To modify thread status to Sticky
	public static final String STICKY_BOOKMARK_THREAD	= "INSERT INTO OI_FM_BOOKMARKS (BOOKMARKID, USERID, THREADID, BKM_STICKY) VALUES (SEQ_OI_FM_BOOKMARKID.NEXTVAL, ?, ?, ?)";
	
//	To assign specific thread to selected Topic
	public static final String MOVE_THREAD_TO_TOPIC	=	"UPDATE OI_FM_THREAD SET TOPICID = ? WHERE THREADID = ? ";
	
//	To get list of postings to print specific thread
	public static final String	PRINT_THREAD_POSTS_LIST = "SELECT POSTID, POSTING, NICKNAME, SIGNATURE, POSTED_BY, TO_CHAR(POSTED_ON, '"+OILabelConstants.DISPLAY_DATE_TIME_FORMAT+"') POSTED_ON, HQREPLY FROM OI_FM_POSTS OFP WHERE THREADID = ? AND MODERATION_STAT = 'Y' ORDER BY POSTID DESC";
	
	/* Added/Modified by Aik Mun @ Jan 19, 2009 */
//	To insert new posting info	-- POSTID, THREADID, POSTING, MODERATION_STAT, USERID, USERID, USERID 
	public static final String	CREATE_POSTING	= "INSERT INTO OI_FM_POSTS (POSTID, THREADID, POSTING, NICKNAME, SIGNATURE, MODERATION_STAT, POSTED_BY, POSTED_ON, HQREPLY,QUOTE_POSTING) SELECT ?, ?, ?, NICKNAME,  DECODE(SHOW_SIGNATURE, 'Y', SIGNATURE, '') SIGNATURE, ?, ?, SYSDATE, ?,? FROM OI_AD_PROFILE AP WHERE USERID=? ";
	
//	To get posting info	
	public static final String	POSTING_DETAILS	= "SELECT POSTID, THREADID, POSTING, NICKNAME, SIGNATURE, POSTED_BY, TO_CHAR(POSTED_ON, '"+OILabelConstants.DISPLAY_DATE_TIME_FORMAT+"') POSTED_ON, NVL(HQREPLY, 'N') HQREPLY FROM OI_FM_POSTS WHERE POSTID = ?";
//	To get posting info	at moderation level
	public static final String	POSTING_MOD_DETAILS	= "SELECT POSTID, POSTING FROM OI_FM_POSTS WHERE THREADID = ?";
	
//	To Modify posting info	
	public static final String	MODIFY_POSTING	= "UPDATE OI_FM_POSTS SET POSTING = ? WHERE POSTID = ?";

//	To delete posting info  
	public static final String DELETE_POSTING = "DELETE OI_FM_POSTS WHERE POSTID = ?";

//	To modify posting moderation status
	public static final String UPDATE_POSTING_MODERATION	= "UPDATE OI_FM_POSTS SET MODERATION_STAT = 'Y', MODERATED_BY = ?, MODERATED_ON = SYSDATE WHERE POSTID IN (:POSTIDS:)";
	
//	To delete Postings when moderator rejects
	public static final String REJECT_POSTING_AUDIT_MODERATION	= "DELETE OI_AD_AUDITTRAIL WHERE POSTID IN (:POSTIDS:)";
	public static final String REJECT_POSTING_MODERATION	= "DELETE OI_FM_POSTS WHERE POSTID IN (:POSTIDS:)";
	
//	To get the moderaion req info for specific thread
	public static final String THREAD_MODERATION_REQ	= "SELECT MODERATION_REQ FROM OI_FM_THREAD WHERE THREADID = ? AND MODERATION_REQ = 'Y'";
	
//	To get the moderaion req info for specific topic
	public static final String THREAD_TOPIC_MODERATION_REQ	= "SELECT MODERATION_REQ FROM OI_FM_TOPIC WHERE TOPICID = ? AND MODERATION_REQ = 'Y'";

//	To get the list of posts or threads, which required moderation
	public static final String MOD_REQ_THREADS_POSTS_LIST	=	"SELECT BOARDID, TOPICID, BOARDNAME, TOPICNAME, PST.THREADID, POSTID, POSTED_ON, POSTED_BY, THREADNAME, POSTING, NICKNAME, SIGNATURE, HQREPLY FROM (SELECT OFB.BOARDID, OFH.TOPICID, THREADID, NAME BOARDNAME, TOPICNAME, TITLE THREADNAME, OFT.MODERATION_STAT FROM OI_FM_BOARDMODADMIN OFBM, OI_FM_BOARD OFB, OI_FM_TOPIC OFH, OI_FM_THREAD OFT WHERE OFBM.BOARDID = OFB.BOARDID AND OFB.BOARDID = OFH.BOARDID AND OFH.TOPICID = OFT.TOPICID AND USERID = ? AND OFT.MODERATION_STAT = ?) BTT, (SELECT THREADID, POSTID, POSTING, NICKNAME, SIGNATURE, TO_CHAR(POSTED_ON, '"+OILabelConstants.DISPLAY_DATE_TIME_FORMAT+"') POSTED_ON, POSTED_BY, HQREPLY FROM OI_FM_POSTS OFP WHERE OFP.MODERATION_STAT = 'N') PST WHERE BTT.THREADID = PST.THREADID ORDER BY BOARDID, TOPICID, THREADID DESC, POSTID DESC";
	public static final String ADMIN_MOD_REQ_THREADS_POSTS_LIST	=	"SELECT BOARDID, TOPICID, BOARDNAME, TOPICNAME, PST.THREADID, POSTID, POSTED_ON, POSTED_BY, THREADNAME, POSTING, NICKNAME, SIGNATURE, HQREPLY FROM (SELECT OFB.BOARDID, OFH.TOPICID, THREADID, NAME BOARDNAME, TOPICNAME, TITLE THREADNAME, OFT.MODERATION_STAT FROM OI_FM_BOARD OFB, OI_FM_TOPIC OFH, OI_FM_THREAD OFT WHERE OFB.BOARDID = OFH.BOARDID AND OFH.TOPICID = OFT.TOPICID AND OFT.MODERATION_STAT = ?) BTT, (SELECT THREADID, POSTID, POSTING, NICKNAME, SIGNATURE, TO_CHAR(POSTED_ON, '"+OILabelConstants.DISPLAY_DATE_TIME_FORMAT+"') POSTED_ON, POSTED_BY, HQREPLY FROM OI_FM_POSTS OFP WHERE OFP.MODERATION_STAT = 'N') PST WHERE BTT.THREADID = PST.THREADID ORDER BY BOARDID, TOPICID, THREADID DESC, POSTID DESC";	

//	To check thread belongs to the same board or not
	public static final String THREAD_BOARD_SAME = "SELECT THREADID, OFH.TOPICID, OFB.BOARDID FROM OI_FM_BOARDMODADMIN OFBM, OI_FM_BOARD OFB, OI_FM_TOPIC OFH, OI_FM_THREAD OFT WHERE OFBM.BOARDID = OFB.BOARDID AND OFB.BOARDID = OFH.BOARDID AND OFH.TOPICID = OFT.TOPICID AND THREADID = ? AND USERID = ?";

//	To check whether allow personal message or not
	public static final String ALLOW_PERSONAL_MESSAGE = "SELECT VALUE FROM OI_AD_CONFIGURATION WHERE TAG = 'PERSONALMESSAGE' AND VALUE = 'Y'";

//	To check whether allow alert admin or not
	public static final String ALLOW_ALERT_ADMIN = "SELECT VALUE FROM OI_AD_CONFIGURATION WHERE TAG = 'ALERTADMIN' AND VALUE = 'Y'";

//	To maintain audit info for thread level (userid, title, thread id, thread id)
	public static final String AUDIT_MOD_THREAD_INFO = "INSERT INTO OI_AD_AUDITTRAIL (AUDITID, TRANSACTION_BY, TRANSACTION_ON, TRANSACTION_TYPE, MODERATED_CONTENT, POSTED_CONTENT, THREADID, POSTEDON, POSTEDBY) SELECT SEQ_OI_AD_AUDITID.NEXTVAL, ?, SYSDATE, 'MT', TITLE, ?, ?, CREATED_ON, CREATED_BY  FROM OI_FM_THREAD WHERE THREADID = ? ";

//	To maintain audit info for Post level (struserid, post cnt, post id, post id)
	public static final String AUDIT_MOD_POST_INFO = "INSERT INTO OI_AD_AUDITTRAIL (AUDITID, TRANSACTION_BY, TRANSACTION_ON, TRANSACTION_TYPE, MODERATED_CONTENT, POSTED_CONTENT, POSTID, THREADID, POSTEDON, POSTEDBY) SELECT SEQ_OI_AD_AUDITID.NEXTVAL, ?, SYSDATE, 'MP', POSTING, ?, ?, THREADID, POSTED_ON, POSTED_BY FROM OI_FM_POSTS WHERE POSTID = ?";

//	To get the prev and next threads in postings list page
	public static final String PREV_NEXT_THREAD = "SELECT ROWNUM, THREADID FROM (SELECT TD.THREADID FROM OI_FM_THREAD TD, (SELECT TG.THREADID, GM.USERID FROM OI_FM_THREAD_GROUPS TG, OI_FM_GROUPMEMBERS GM WHERE TG.GROUPID = GM.GROUPID AND GM.USERID= ?) TM WHERE TD.THREADID = TM.THREADID(+) AND MODERATION_STAT = 'Y' AND ((TM.USERID= ? AND TD.SECURITY='Y') OR TD.SECURITY ='N' OR TD.CREATED_BY= ?) AND TD.TOPICID= ? ORDER BY TD.LASTPOST_ON, TD.THREADID)";

//	To delete thread audit
	public static final String DELETE_AUDIT_THREAD = "DELETE OI_AD_AUDITTRAIL WHERE THREADID = ?";
	
//	To delete posting audit
	public static final String DELETE_AUDIT_POSTING = "DELETE OI_AD_AUDITTRAIL WHERE POSTID = ?";
	
	//To get the Mail Ids of the Bookmarked users
	public static final String BOOKMARK_MAILIDS = "SELECT EMAILID FROM OI_AD_PROFILE PF WHERE PF.USERID IN (select USERID from OI_FM_BOOKMARKS bk where bk.THREADID = ? and bk.BKM_STICKY='B')";
	
	public static final String  THREADNPOST_DETAILS = "select b.THREADID, TOPICID, TITLE, MODERATION_REQ, b.MODERATION_STAT,b.MODERATED_BY, b.MODERATED_ON, LASTPOST_ID, LASTPOST_ON,SECURITY, REPLIES, HITS, LOCKED, CREATED_BY, CREATED_ON from OI_FM_POSTS a,OI_FM_THREAD b 	where a.threadid = b.threadid	and a.threadid = ?";
	
	//	Anbu To get the total posts for specific thread
	public static final String	THREAD_POSTS_CNT_USER = "SELECT COUNT(POSTID) FROM OI_FM_POSTS WHERE MODERATION_STAT = 'Y' AND THREADID = ?";
 	public static final String INSERT_STICKY_ADMIN_BOOKMARK_THREAD	= "INSERT INTO OI_FM_BOOKMARKS (BOOKMARKID, USERID, THREADID, BKM_STICKY) VALUES (SEQ_OI_FM_BOOKMARKID.NEXTVAL, ?, ?, ?)";
 	public static final String UPDATE_STICKY_ADMIN_BOOKMARK_THREAD	= "UPDATE OI_FM_BOOKMARKS SET THREADID =? WHERE BOOKMARKID =? ";
 	//public static final String ADMIN_STICKY_THREAD_EXISTS	= "SELECT 'Y' FROM OI_FM_BOOKMARKS WHERE USERID = ? AND THREADID = ? AND BKM_STICKY = ?";
 	public static final String ADMIN_STICKY_THREAD_EXISTS	= "SELECT 'Y',BOOKMARKID FROM OI_FM_BOOKMARKS WHERE BKM_STICKY = ? ";
 
 	//public static final String GET_THRD_ID	= "SELECT  THREADID,THREADNAME FROM OI_FM_BOOKMARKS WHERE BKM_STICKY = ? ";
 	
 	public static final String GET_THRD_ID	= "SELECT  A.THREADID,TITLE THREADNAME FROM OI_FM_BOOKMARKS A,OI_FM_THREAD B WHERE A.THREADID=B.THREADID AND BKM_STICKY = ? ";
 	
 
 	/* Added/Modified by Aik Mun @ Jan 16, 2009 */
 	public static final String INSERT_MARK_READED = "INSERT INTO OI_FM_READ_POST (USERID, THREADID, POSTID,READ_ON) VALUES (?,?,?,SYSDATE)";
 	public static final String DELETE_MARK_READED = "DELETE OI_FM_READ_POST WHERE USERID = ? AND THREADID = ?  AND POSTID = ?";
 	public static final String CHECK_READED = "SELECT POSTID FROM OI_FM_READ_POST WHERE USERID = ? AND THREADID = ? AND POSTID IN (";

}